config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:index, :show]
  resources :analytics

  post "search", to: "search#search"
  get "show", to: "articles#show"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search, against: %i[title], using: {
                             tsearch: { prefix: true },
                           }

  validates :title, presence: true
  validates :body, presence: true
end

app/models/query.rb
class Query < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search, against: :query,
                           using: :trigram
  scope :user, lambda { |user_id|
    where(user_id: user_id)
  }

  validates :user_id, presence: true
  validates :query, presence: true
  validates :identifier, presence: true
end

app/models/search_handler.rb
class SearchHandler
  def initialize(data, ip)
    @query = data[:search].gsub(/[^0-9A-Za-z ]/, "")
    @identifier = data[:identifier]
    @user_id = ip
  end

  def search
    @results = Article.search(@query).limit(6)
    if @results.blank?
      { error_message: ["We were not able to find any results for search '#{@query}'"], error_code: 404 }
    else
      { data: @results, errors: [] }
    end
  end

  def save_activity
    @query_form_activity = Query.find_by(identifier: @identifier)
    @increment_query = Query.find_by(user_id: @user_id, query: @query)
    @similar_queries = Query.search(@query).user(@user_id).where(identifier: @identifier)
    @increment_query.nil? ? create_new_query : increment_query

    decrement_query_counter if !part_of_session? && !@query_form_activity.nil?

    @similar_queries.each do |query|
      query.delete if included_and_shorter(query.query)
    end
  end

  private

  def included_and_shorter(query)
    @query.include?(query) && query.length < @query.length
  end

  def part_of_session?
    @query_form_activity.counter == 1 unless @query_form_activity.nil?
  end

  def new_query?
    !@query_form_activity.nil? && @query.include?(@query_form_activity.query)
  end

  def create_new_query
    @new_query = Query.create!(user_id: @user_id, identifier: @identifier, found: !@results.blank?, query: @query)
  end

  def increment_query
    @increment_query.update(identifier: @identifier, counter: @increment_query.counter + 1)
  end

  def decrement_query_counter
    @query_form_activity.update(counter: @query_form_activity.counter - 1, identifier: 0)
  end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  before_action :current_user

  def index
    @queries = Query.where(user_id: @current_user).order(:counter)
    @total_searches = @queries.reduce(0) { |sum, num| sum + num.counter }
    @successfull_searches = @queries.select(&:found?)
    @unsuccessfull_searches = @queries.reject(&:found)
    @total_articles = Article.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :turbo_frame_request_variant

  protected

  def current_user
    @current_user ||= request.remote_ip.to_s.gsub(/[^0-9A-Za-z]/, "").to_i
  end

  def render_error(error_code, error_message)
    render json: { data: [], errors: error_message }, status: error_code
  end

  private

  def turbo_frame_request_variant
    request.variant = :turbo_frame if turbo_frame_request?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :current_user

  def index
    @articles = Article.all
  end

  def show
    @results = Article.all
    if @results.blank?
      { error_message: ["We were not able to find any results for search '#{params[:search]}'"], error_code: 404 }
    else
      render json: { data: @results, errors: [] }
    end
  end
end

#   def index
#     if params[:search].present?
#       @articles = Article.where("title LIKE ?", "#{params[:search]}")
#     else
#       @articles = Article.all
#     end
#   end
# end

#   @articles = if params[:search]
#       Article.search(params[:search])
#     else
#       Article.all
#     end
# end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :current_user

  def index; end

  def search
    result = search_handler.search
    search_handler.save_activity
    if result[:error_code]
      return render_error(result[:error_code], result[:error_message])
    else
      render json: result, status: :ok
    end
  end

  private

  def search_handler
    @search_service ||= SearchHandler.new(permitted_params, @current_user)
  end

  def permitted_params
    params.permit(:search, :user_id, :identifier)
  end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/analytics/index.html.erb
<div class="dashboard-wrapper">
  <div class='numbers-wrapper'>
    <div class="number-of-searches">
      <div class='total-searches numbers-analytic'>
        <div class='header'>
          Searches
        </div>
        <div class='number'>
          <%=@total_searches%>
        </div>
      </div>
      <div class='successful-searches numbers-analytic'>
        <div class='header'>
          Successful searches
        </div>
        <div class='number'>
          <%=@successfull_searches.reduce(0){|sum, num| sum + num.counter}%>
        </div>
      </div>
      <div class="number-of-articles numbers-analytic">
        <div class='header'>
          Articles
        </div>
        <div class='number'>
          <%=@total_articles%>
        </div>
      </div>
      <div class='unsuccesfull-searches numbers-analytic'>
        <div class='header'>
          Unsuccessful searches
        </div>
        <div class='number'>
          <%=@unsuccessfull_searches.reduce(0){|sum, num| sum + num.counter}%>
        </div>
      </div>
    </div>
    <div class="most-searched">
      <%= line_chart Query.where(user_id: @current_user).group_by_minute(:updated_at).count, ytitle: "Searches per minute" %>
    </div>
  </div>
  <div class='searches-wrapper'>
    <div class="found-searches">
      <ul>
        <li class='table-head'>
          <div class='search-counter'>Count</div>
          <div class="search-query">Successfull Search Query</div>
        </li>
        <% @successfull_searches.reverse.take(7).each do |search|%>
          <li>
            <div class='search-counter'><%= search.counter%></div>
            <div class='search-query'><%= search.query%></div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="not-found-searches">
      <ul>
        <li class='table-head'>
          <div class='search-counter'>Count</div>
          <div class="search-query">Unsuccessfull Search Query</div>
        </li>
        <% @unsuccessfull_searches.reverse.take(7).each do |search|%>
          <li>
            <div class='search-counter'><%= search.counter%></div>
            <div class='search-query'><%= search.query%></div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/articles/_article_tile.html.erb
<div id="user-tile">
  <div id="article-title">
    <h2><%=article.title %></h2>
  </div>
  <div id="article-body">
    <p><%=article.body %></p>
  </div>
</div>

app/views/articles/index.html.erb
<div id="article-list">
  <div class="search-box-wrapper">
    <input type="text" name="search" id='index-search-box' placeholder="Search..." onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search...'">
  </div>
  <ul id="filter-articles">
    <% @articles.each do |article| %>
      <li>
        <%= render "article_tile", article: article %>
      </li>
    <%end%>
  </ul>
  <div id="render-list"></div>
</div>

app/views/layouts/_navbar.html.erb
<nav id="navbar">
  <ul>
    <li><%= link_to "SEARCH", root_path, method: :get %></li>
    <li><%= link_to "ANALYTICS", analytics_path, method: :get %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Custom-Search</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render "layouts/navbar"%>
    <%= yield %>
  </body>
</html>